services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    image: python:3.12-slim
    restart: unless-stopped
    working_dir: /app
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: twiclone.settings
      DEBUG: "1"
      PGHOST: db
      PGPORT: "5432"
    volumes:
      - ./app:/app
      - ./media:/app/media
    command: >
      bash -lc "
      pip install --no-cache-dir -r requirements.txt &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
